# Generated by Django 5.1 on 2024-08-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر', null=True, upload_to='posts'),
        ),
    ]
