# Generated by Django 5.0 on 2024-07-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
